apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bofufftnm-go 
  janus-idp.io/tekton: bofufftnm-go
  backstage.io/kubernetes-id: bofufftnm-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bofufftnm-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml